name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*, 17.x]

    steps:
      - name: Checkout LAMS
        uses: actions/checkout@v2-beta
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install LAMS (Dev)
        run: |
          mv npm-shrinkwrap.dev.json npm-shrinkwrap.json
          npm ci
      - name: Lint
        run: npm run lint
      - name: Install js-yaml (optional dependency)
        run: npm install --no-save js-yaml
      - name: Run tests
        run: npm test
        env:
          CI: true